In [4]:
import pandas as pd
import numpy as np

file = "atz/atz_patch_dataset__3_128_27_v3_10%_30_99%_multiple_refbox.csv"

In [5]:
ls

Untitled.ipynb  atz/

In [6]:
df = pd.read_csv(file)

In [7]:
df.head()

,Unnamed: 0,image,threat_present,front_back,patch_id,label,label_txt,global_x1y1x2y2,relative_x1y1x2y2,anomaly_size,x1x2y1y2,subject_gender,subject_id
0,0,S_P_M5_MD_F_W_SS_V_W_back_0906085926.jpg,1,back,0,0,NORMAL0,NaN,NaN,0,"(0, 128, 0, 128)",M,M5
1,1,S_P_M5_MD_F_W_SS_V_W_back_0906085926.jpg,1,back,1,0,NORMAL0,NaN,NaN,0,"(103, 231, 0, 128)",M,M5
2,2,S_P_M5_MD_F_W_SS_V_W_back_0906085926.jpg,1,back,2,0,NORMAL0,NaN,NaN,0,"(206, 334, 0, 128)",M,M5
3,3,S_P_M5_MD_F_W_SS_V_W_back_0906085926.jpg,1,back,3,0,NORMAL0,NaN,NaN,0,"(0, 128, 103, 231)",M,M5
4,4,S_P_M5_MD_F_W_SS_V_W_back_0906085926.jpg,1,back,4,0,NORMAL0,NaN,NaN,0,"(103, 231, 103, 231)",M,M5

In [14]:
df = df[df['relative_x1y1x2y2'].notna()]

In [ ]:
df.sort_values(['image', 'label_txt'])

In [16]:
df.sort_values(['image', 'label_txt'])[df['image'] == 'D_P_F1_CK_F_LA_WB_F_S_front_0907140855.jpg']

/var/folders/4w/d_tk0h2x7cgbl6q1vqw8dv6c0000gq/T/ipykernel_1647/2082584023.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df.sort_values(['image', 'label_txt'])[df['image'] == 'D_P_F1_CK_F_LA_WB_F_S_front_0907140855.jpg']

,Unnamed: 0,image,threat_present,front_back,patch_id,label,label_txt,global_x1y1x2y2,relative_x1y1x2y2,anomaly_size,x1x2y1y2,subject_gender,subject_id
36932,36932,D_P_F1_CK_F_LA_WB_F_S_front_0907140855.jpg,1,front,5,13,CK,"(269, 173, 315, 243)","(63, 70, 109, 128)",2726,"(206, 334, 103, 231)",F,F1
36935,36935,D_P_F1_CK_F_LA_WB_F_S_front_0907140855.jpg,1,front,8,13,CK,"(269, 173, 315, 243)","(63, 0, 109, 37)",1786,"(206, 334, 206, 334)",F,F1
36937,36937,D_P_F1_CK_F_LA_WB_F_S_front_0907140855.jpg,1,front,10,11,WB,"(155, 375, 194, 495)","(52, 66, 91, 128)",2480,"(103, 231, 309, 437)",F,F1
36940,36940,D_P_F1_CK_F_LA_WB_F_S_front_0907140855.jpg,1,front,13,11,WB,"(155, 375, 194, 495)","(52, 0, 91, 83)",3360,"(103, 231, 412, 540)",F,F1